version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: ./app/frontend/Dockerfile.frontend
    image: poolkit/anomaly-frontend:latest
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./app/backend/Dockerfile.backend
    image: poolkit/anomaly-backend:latest