FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

ENV NAME Backend

CMD ["uvicorn", "web-app.backend.endpoint:app", "--host", "0.0.0.0", "--port", "8000"]